### ISSUE TITLE
edge fading

### ISSUE THREAD

**Issue by shadowninja55** [AristideBH/Marqueeck#6]
first of all, i wanted to thank you for creating this library. of the three i've tested for svelte, it's the only one i've had no issues with out of the box. i was wondering if it would be possible to add a feature to fade the edges of the marquee, similar to the first example here https://svelte-marquee.vercel.app/ ?

**Comment by AristideBH** [comment]
Hello, and thanks for your support !
As it's mostly a styling feature, and I tried to keep the styling to a minimum, I don't think I'll directly implement it. 

However, looking at the implementation of your reference, I suggest to simply create a class and pass it to the component : 
```css
.edge-fading {
  mask-image: linear-gradient(
    to right, 
    transparent 0%, rgba(0, 0, 0, 1.0) 10%, rgba(0, 0, 0, 1.0) 90%, transparent 100%
  );
}
```
